### ISSUE TITLE
Question about temporal dependencies and feature correlations captured by DMSA

### ISSUE THREAD

**Issue by Stinger-Wiz** [WenjieDu/SAITS#11]
你好，关于文章当中的自注意力我有问题想请教您。维度为N×N的自注意力矩阵Q·Kt，表示的是长度为N的一种维度之间的注意力关系，而您文章中提到的“Such a mechanism makes DMSA able to capture the temporal dependencies and feature correlations between time steps in the high dimensional space with only one attention operation”，DMSA的一个注意力矩阵能一次性同时捕获到两种维度之间的注意力，想问一次注意力操作捕获到两种类型的注意力是怎么做到的。

**Comment by WenjieDu** [comment]
Hi there,<br><br>Thank you so much for your attention to SAITS! If you find SAITS is helpful to your work, please star⭐️ this repository. Your star is your recognition, which can let others notice SAITS. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you again for your patience! 😃<br><br>Best,<br>Wenjie

**Comment by Will-Hor** [comment]
I have a time series dataset where each column represents a different time series. 
My understanding is that feature correlation describes the relationship between different time series, while temporal dependence describes the correlation between different time points within the same time series. 

I am also puzzled about how a single attention operation can capture both temporal dependence and feature correlation? 

Looking forward your reply

**Comment by WenjieDu** [comment]
In [^1], BRITS utilizes LSTM to produce history-based estimation and builds another component to produce feature-based estimation (please refer to Section 4.3 in [^1]), and then combines both of them to form the final imputation. 

We claim DMSA can capture the temporal dependencies and feature correlations between time steps with **only one attention operation** because, different from BRITS, we only need one DMSA, which can capture the temporal and feature correlations between time steps. The attention map has already embedded temporal dependencies between time steps. With diagonal masks applied, as we introduced in Section 3.2.1, input values at the t-th step can not see themselves and are prohibited from contributing to their own estimations. Consequently, estimations of the t-th step only depend on input values from other steps. It's worth mentioning that the component in BRITS to produce feature-based estimation is specially built to consider correlations between features of each time step, and its input is imputed data of the current step from the LSTM cell, namely this component works on the feature dimension. But DMSA works on the time dimension (this is why captured temporal dependencies and feature correlations are both between time steps). Due to that DMSA's input has already been projected into high dimensions (the features are fused) and SAITS does not make the imputation at this stage, DMSA does not need BRITS' component.

[^1]: Cao, W., Wang, D., Li, J., Zhou, H., Li, L., & Li, Y. (2018). [BRITS: Bidirectional Recurrent Imputation for Time Series](https://papers.nips.cc/paper/2018/hash/734e6bfcd358e25ac1db0a4241b95651-Abstract.html). NeurIPS 2018.

**Comment by Stinger-Wiz** [comment]
How should we understand the phrase 'DMSA works in the time dimension'? If attention maps represent the attention between each time step, where is the correlation between features reflected?

Looking forward your reply🌹

**Comment by WenjieDu** [comment]
Hi, guys @Stinger-Wiz @Will-Hor, does my previous reply sound reasonable to you? If you have any other questions about this issue, feel free to tell me :-)

**Comment by Stinger-Wiz** [comment]
Thank you for your detailed explanation, now there is no problem with this research, thank you for your assistance :-)

**Comment by WenjieDu** [comment]
@Stinger-Wiz My pleasure. Also thank you very much for your attention to SAITS! If you think it is inspiring or helpful to your work, please star🌟 repo to help more people notice this work. Also please take a look at our new work [PyPOTS](https://github.com/WenjieDu/PyPOTS) which may be useful. 😃 Many thanks for your contribution again!

**Comment by Will-Hor** [comment]
thank you very much. Your reply really helped me a lot.

**Comment by WenjieDu** [comment]
@Will-Hor No problem, William! 😉 If you like SAITS, please star this repository. Thanks!
