### ISSUE TITLE
pd.concat 

### ISSUE THREAD

**Issue by lidamsoukaina** [WenjieDu/SAITS#12]
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

**Comment by WenjieDu** [comment]
Hi there,<br><br>Thank you so much for your attention to SAITS! If you find SAITS is helpful to your work, please star⭐️ this repository. Your star is your recognition, which can let others notice SAITS. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you again for your patience! 😃<br><br>Best,<br>Wenjie

**Comment by WenjieDu** [comment]
Right, I noticed this warning while building PyPOTS. I didn't update the code in this repo because the versions of the dependencies are fixed in `conda_env_dependencies.yml` so I thought it wouldn't be a problem. Considering users may copy and use the code in their own dev env, the warning you point out here can possibly cause problems in the future. I'm going to create a PR to help solve this issue. I will reference the PR here and invite you to review the code. Thank you very much for your contribution, Soukaina! 👍

**Comment by WenjieDu** [comment]
PR #13 has been created. @lidamsoukaina Please review the code. 😊
